version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter
      MYSQL_USER: ashway
      MYSQL_PASSWORD: ashway
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  node:
    build: .
    container_name: node
    command: npm run start
    volumes:
      - ..:/usr/app
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_data: