version: '3.8'
services:
  db:
    build: ./db
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/init
  node:
    build: ./node
    container_name: node
    command: npm run start
    volumes:
      - ../src:/usr/app/src
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_data: