version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter
      MYSQL_USER: ashway
      MYSQL_PASSWORD: ashway
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ../database/twitter.sql:/docker-entrypoint-initdb.d/twitter.sql
  web:
    image: nginx:latest
    container_name: web
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../src:/usr/share/nginx/html
volumes:
  db_data: